package YACTTest::Conferences;

use strict;
use warnings;
use utf8;

#  __   __ _    ____ _____ ___ _   _ ___
#  \ \ / // \  / ___|_   _|_ _| \ | |_ _|
#   \ V // _ \| |     | |  | ||  \| || |
#    | |/ ___ \ |___  | |_ | || |\  || |
#    |_/_/   \_\____| |_(_)___|_| \_|___|
# ----------------------------------------

my %conf_config = (
  qh2012eu => {
    'subsection' => {
                      'subsection_other_test' => '2',
                      'subsection_other_other_test' => '2'
                    },
    'levels' => {
                  'level1_name_en' => 'Beginner'
                },
    'payment' => {
                   'open' => '1',
                   'products' => 'registration',
                   'type' => 'YEF',
                   'currency' => 'EUR',
                   'invoices' => '0'
                 },
    'talks' => {
                 'submissions_open' => '1',
                 'durations' => '5 40',
                 'submissions_notify_language' => 'en',
                 'notify_accept' => '1',
                 'start_date' => '2012-12-06 08:00:00',
                 'levels' => '1',
                 'edition_open' => '0',
                 'end_date' => '2012-12-09 23:00:00',
                 'submissions_notify_address' => 'getty@duckduckgo.com',
                 'show_schedule' => '1'
               },
    'product_registration_price1' => {
                                       'amount' => '20',
                                       'name_en' => 'standard'
                                     },
    'static' => {
                  'root' => 'http://quackandhack.com/'
                },
    'rooms' => {
                 'r2_name_en' => 'Agora',
                 'r1_name_en' => 'Classe numerique',
                 'rooms' => 'r1 r2'
               },
    'registration' => {
                        'open' => '1',
                        'max_attendees' => '3',
                        'gratis' => '0'
                      },
    'flickr' => {
                  'tags' => 'qh2012eu'
                },
    'general' => {
                   'languages' => 'en',
                   'default_country' => 'fr',
                   'timezone' => 'Europe/Paris',
                   'other_conference_base' => 'http://quackandhack.com/qh2012eu/,http://quackandhack.com/eu/',
                   'name_en' => 'Quack and Hack 2012 Europe Sample',
                   'default_language' => 'en',
                   'conference_base' => 'http://quackandhack.com/2012eu/'
                 },
    'product_registration' => {
                                'name_en' => 'Registration',
                                'prices' => '1'
                              }
  },
  ye2013 => {},
  yn2013 => {},
);

use Path::Class;
use Config::INI::Writer;
use File::Tempdir;
use Path::Class;
use IO::All;
use File::chdir;

sub init { 
  my ( $yact ) = @_;
  my $fake_remotes = dir($yact->config->root,'fakeremotes');
  mkdir $fake_remotes;
  my %conf_ini = (
    'qh2012eu/subsection' => {
                               'subsection_other_test' => '1',
                               'subsection_test' => '1'
                             },
    'qh2012eu' => {
                    'section_other_test' => '1',
                    'section_test' => '1'
                  },
  );
  for my $conf_name (qw( qh2012eu ye2013 yn2013 )) {
    my $fake_remote = dir($fake_remotes,$conf_name);
    mkdir $fake_remote;
    $conf_ini{$conf_name} = {} unless defined $conf_ini{$conf_name};
    $conf_ini{$conf_name}->{remote} = $fake_remote;
  }
  Config::INI::Writer->write_file(\%conf_ini,file($yact->config->root,'confs.ini'));
  for (keys %conf_ini) {
    init_conference($yact,$conf_ini{$_}->{remote},$_) unless defined $conf_ini{$_}->{remote};
  }
  fill_test_database($yact);
}

sub init_conference {
  my ( $yact, $fake_remote, $conf_name ) = @_;

  return unless $fake_remote;

  my $temp = File::Tempdir->new;

  system( "git init " . $fake_remote . " --bare" );
  system( "git clone file://" . $fake_remote . " " . $temp->name );

  Config::INI::Writer->write_file($conf_config{$conf_name},file($temp->name,'yact.ini'));

  {
      local $CWD = $temp->name;
      system("git add .");
      system("git commit -m'Generated by YACTTest::Conferences'");
      system("git push -u origin master");
  }
}


#   ____        _        _
#  |  _ \  __ _| |_ __ _| |__   __ _ ___  ___
#  | | | |/ _` | __/ _` | '_ \ / _` / __|/ _ \
#  | |_| | (_| | || (_| | |_) | (_| \__ \  __/
#  |____/ \__,_|\__\__,_|_.__/ \__,_|___/\___|
# --------------------------------------------- 

sub fill_test_database {
    my ($yact) = @_;
    my $db     = $yact->db;
    scalar $db->populate(
        'User',
        [

            [   qw( login passwd salutation first_name last_name nick_name pseudonymous country town web_page email pause_id language timezone photo_name )
            ],

            [   'test1',            'test1',
                undef,              'Long Lang',
                'Too Kool',         undef,
                0,                  'de',
                '',                 'http://test.de/',
                'test@act.yapc.eu', 'BLA',
                'de',               'Europe/Berlin',
                undef
            ],
            [   'test2',            'test2',
                1,                  'Überzone',
                'Drops the tone',   'Pseudo1',
                1,                  'uk',
                'London',           'http://test.de/',
                'test@act.yapc.eu', '',
                'en',               'Europe/Berlin',
                'test2.jpg'
            ],
            [   'test3',            'test3',
                3,                  'Perl',
                'Ganz Lang',        undef,
                0,                  'jp',
                '',                 'http://test.de/',
                'test@act.yapc.eu', '',
                'jp',               'Europe/Berlin',
                'test3-user.jpg'
            ],
            [   'test',             'test',
                undef,              'Peter',
                'Hallo',            'Pseudo2',
                1,                  'at',
                'Wien',             'http://test.de/',
                'test@act.yapc.eu', '',
                'at',               'Europe/Berlin',
                'test.jpg'
            ],
            [   '1test',            '1test',
                1,                  'Paul',
                'Overlord',         undef,
                0,                  'ru',
                '',                 '',
                'test@act.yapc.eu', 'BLUB',
                'ru',               'Europe/Berlin',
                '1test.jpg'
            ],
            [   'tt_tt',            'tt_tt',
                3,                  'Marry',
                'Ho',               'Pseudo3',
                1,                  'de',
                'Dresden',          '',
                'test@act.yapc.eu', '',
                'de',               'Europe/Berlin',
                'tt_tt.jpg'
            ],
            [   '_test',            '_test',
                undef,              'Sèbastian',
                'Frenchman',        'Pseudo4',
                0,                  'fr',
                undef,              undef,
                'test@act.yapc.eu', '',
                'fr',               'Europe/Berlin',
                '_test.jpg'
            ],
            [   'test_',            'test_',
                1,                  'Sébastian',
                'Englishman',       'Pseudo5',
                1,                  'us',
                'Philadelphia',     '',
                'test@act.yapc.eu', '',
                'en',               'Europe/Berlin',
                'test_.jpg'
            ],
            [   'gfuji',             'none',
                undef,               '藤 吾郎',
                '',                  'gfx',
                0,                   'jp',
                'Tōkyō',           'http://d.hatena.ne.jp/gfx/',
                'gfuji(at)cpan.org', 'GFUJI',
                'ja',                'Asia/Tokyo',
                'gfuji.jpg'
            ],
            [   'vti',                    'none',
                undef,                    'Вячеслав',
                'Тихановский', 'vti',
                0,                        'ua',
                'Киев',               'http://showmetheco.de/',
                'vti(at)cpan.org',        'VTI',
                'uk',                     'Europe/Kiev',
                undef
            ],
            [   'azawawi',
                'none',
                undef,
                'أحمد محمد زواوي',
                '',
                'azawawi',
                0,
                'jo',
                'Amman',
                'http://ahmadzawawi.blogspot.com/',
                'ahmad.zawawi(at)gmail.com',
                'AZAWAWI',
                'ar',
                'Asia/Amman',
                undef
            ],
            [   'nuffin',
                'none',
                undef,
                'יובל',
                "קוג'מן",
                'nothingmuch',
                0,
                'il',
                'Tel Aviv',
                'http://nothingmuch.woobling.org/',
                'nothingmuch(at)woobling.org',
                'NUFFIN',
                'he',
                'Asia/Jerusalem',
                'nuffin.jpg'
            ],

            #[
            #    'login', 'passwd',
            #    'salutation', 'first_name', 'last_name',
            #    'nick_name', 'pseudonymous',
            #    'country', 'town',
            #    'web_page', 'email',
            #    'pause_id', 'language', 'timezone', 'photo_name'
            #],

        ]
    );
    scalar $db->populate(
        'Event',
        [

            [   qw( conf_id title abstract url_abstract room duration datetime )
            ],
            [   'qh2012eu',
                'Coffee Break',
                'Are you kidding? Coffee is available all the time. Stop breaking. Go hacking!',
                '',
                'Classe Numérique',
                '10',
                '11:00',
            ],
            [   'ye2013',
                'Coffee/Tee Break',
                'Relax, chat, talk to others while having a hot beverage',
                'http://www.starbucks.com/',
                'Agora',
                '20',
                '16:00',
            ],
            [   'yn2013', 'Welcome',
                'Welcome talk.
                Introduction talk to the event.
                Free breakfast (coffee, tea, juices, pastries, yegg and beacon',
                '',   'Main Hall',
                '30', '09:30',
            ],
            [   'qh2012eu',
                'Coffee Break',
                'Are you kidding? Coffe is available all the time. Stop breaking. Go hacking!',
                undef,
                'Classe Numérique',
                '10',
                '11:00',
            ],
            [   'qh2012eu',
                'コーヒーブレイク',
                'コーヒーブレイク is provided to you by Google translate. I hope it is not rude.',
                '',
                'Agora',
                '20',
                '16:00',
            ],
            [   'qh2012eu',
                'Coffee Break',
                'Are you kidding? Coffe is available all the time. Stop breaking. Go hacking!',
                '',
                'Classe Numérique',
                '10',
                '11:00',
            ],
        ],
    );

    my $qh2012eu = $yact->get_conference('qh2012eu');

    # DO NOT ADD MORE PARTICIPATION - THE CONFERENCE IS FULL!
    $qh2012eu->add_participation( $yact->get_user('test1'), 'XL',  0 );
    $qh2012eu->add_participation( $yact->get_user('test2'), 'XXL', 0 );
    $qh2012eu->add_participation( $yact->get_user('test3'), 'M',   2 );
    #########################################################

    $qh2012eu->add_user_right( $yact->get_user('test1'), 'admin' );
    $qh2012eu->add_user_right( $yact->get_user('test3'), 'treasurer' );
    $qh2012eu->add_user_right( $yact->get_user('test3'), 'talks_admin' );
    $qh2012eu->add_user_right( $yact->get_user('test3'), 'wiki_admin' );

    $qh2012eu->add_track( 'Main Track', 'Inside of a museum!' );

    my $ye2013 = $yact->get_conference('ye2013');

    $ye2013->add_user_right( $yact->get_user('test2'),  'admin' );
    $ye2013->add_user_right( $yact->get_user('_test'),  'talks_admin' );
    $ye2013->add_user_right( $yact->get_user('nuffin'), 'wiki_admin' );
    $ye2013->add_user_right( $yact->get_user('test3'),  'treasurer' );

    $ye2013->add_track( 'Good Track', 'Heaven' );
    $ye2013->add_track( 'Bad Track',  'Hell' );
    $ye2013->add_track( 'Evil Track', 'London' );

    $ye2013->add_participation( $yact->get_user('test1'),   'XL',  0 );
    $ye2013->add_participation( $yact->get_user('test2'),   'XXL', 1 );
    $ye2013->add_participation( $yact->get_user('nuffin'),  'S',   0 );
    $ye2013->add_participation( $yact->get_user('azawawi'), 'L',   0 );
    $ye2013->add_participation( $yact->get_user('gfuji'),   'S',   0 );
    $ye2013->add_participation( $yact->get_user('_test'),   'M',   0 );

}

1;